### ISSUE TITLE
IoBroker Script is failing

### ISSUE THREAD

**Issue by dlindenschmitt** [hosssa/hoymiles-web-api#2]
Hi!

I have set up the API on the local server and is working for the URL-Mode. Tried to integrate the delivered Iobroker Script, which is sadly failing with the following prompt:

`javascript.0 (3321) script.js.BKW.get_data_bkw: ReferenceError: httpGet is not defined at script.js.BKW.get_data_bkw:42:9 at new Promise (<anonymous>) at get (script.js.BKW.get_data_bkw:41:12) at Object.<anonymous> (script.js.BKW.get_data_bkw:32:5) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1620:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7)`

Tried a workaround for the HttpGet Error, but didnt manage it properly. I guess the error is of some missing dependencies.

Best regards!

**Comment by hosssa** [comment]
@dlindenschmitt This rather seems to be an issue with the iobroker javascript engine then. Does [httpGet](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#httpget) work in a different script? Maybe try to update the iobroker javascript adapter.

**Comment by leopard330** [comment]
Port 5000 will not work in the iobroker script
